# .air.toml

# Choose the entry point for your application (change it as needed)
root = "./app"
tmp_dir = "./app/tmp"

[build]
cmd = "go build -o main ."
watch = ["*.go", "controllers/**/*.go", "models/**/*.go"]

[run]
cmd = "main"