version: '3'
services:
  postgres:
    build:
      context: ./postgres
      dockerfile: Dockerfile
    container_name: gthub-postgres-container
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    networks:
      - tghubnet

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gthub-go-app-container
    ports:
      - "${APP_PORT}:8080"
    volumes:
      - ./app:/app
    depends_on:
      - postgres
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: ${DB_PORT}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    networks:
      - tghubnet
  
  pgadmin:
    image: dpage/pgadmin4
    container_name: gthub-pgadmin-container
    ports:
      - "${PGADMIN_PORT}:80"
    environment: 
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      PGADMIN_DEFAULT_PASSWORD_FILE: ${PGADMIN_DEFAULT_PASSWORD_FILE} 
    networks:
      - tghubnet

networks:
  tghubnet:
    driver: bridge

volumes:
  data:
