FROM golang:latest

RUN apt-get update && apt-get install -y wget

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

ENV GO111MODULE=on

WORKDIR /app/cmd/app

# Build the application
RUN go build -o /cmd/app/tmp .

# Define the command to run your application in production
CMD ["./tmp/main"]