FROM golang:latest

RUN apt-get update && apt-get install -y wget

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

ENV GO111MODULE=on

# Build the application
RUN go build -buildvcs=false -o /app/tmp/main .

# Define the command to run your application in production
CMD ["/app/tmp/main"]