version: '3'
services:
  postgres:
    build:
      context: ./postgres
      dockerfile: Dockerfile
    container_name: pi-gravity-postgres-container
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    networks:
      - pigravitynet
  app:
    build:
      context: .
      dockerfile: Dockerfile.production
    container_name: pi-gravity-api-container
    ports:
      - "${APP_PORT}:8090"
    volumes:
      - ./:/app
    depends_on:
      - postgres
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    networks:
      - pigravitynet
  pgadmin:
    image: dpage/pgadmin4
    container_name: pi-gravity-pgadmin-container
    ports:
      - "${PGADMIN_PORT}:80"
    environment: 
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD} 
    networks:
      - pigravitynet

networks:
  pigravitynet:
    driver: bridge